### ISSUE TITLE
Specify which jars to copy manually

### ISSUE THREAD

**Issue by pupeno** [pupeno/jar-copier#1]
At this point, this plug in only implements copying the jars that are specified as the java-agents as this was the goal for this plug in. Extending it to be able to copy other jars, even manually specified ones won't be hard, but it'll be only implemented if clearly needed.

If you need this, please, comment on this issue and/or send a pull request. This is in our roadmap but won't happen until it's needed.

**Comment by dtanzer** [comment]
I am using jar copier for a dependency that is not a java agent. For now, I have declared it as a java agent so jar-copier will pick it up. Anyway, this is just a workaround, so I would love to see this issue fixed.

Please note: I only copy on of my dependencies, so it would be great if I could manually specify which dependencies should be copied.

**Comment by pupeno** [comment]
I didn't know if this use case existed. Thanks for reporting it. Can you provide more information about the case? I'm curious.

**Comment by dtanzer** [comment]
I have a dependency, and I want to deploy it in the resources folder of my ring server, so others can download it or use it with UrlClassloader. The server does not use this code, it only provides it for others. The idea is that the server should always contain this library in the correct version.

It's probably a very rare use case :) And for now, I can live with marking it as a java agent...

**Comment by pupeno** [comment]
This is now released, in version 0.3.0.
