### ISSUE TITLE
Issue a new release to get "Coping" -> "Copying" fix live

### ISSUE THREAD

**Issue by cap10morgan** [pupeno/jar-copier#5]
It may seem like a small thing, but can you roll a new release to get the log message misspelling fix from #4 live? Thank you!

**Comment by pupeno** [comment]
Yes, I'll try to do it soon.

**Comment by cap10morgan** [comment]
Great, thanks @pupeno!

**Comment by pupeno** [comment]
Hey. My apologies for the delay. This is now released. Be aware that I changed the group id: https://clojars.org/com.pupeno/jar-copier/versions/0.4.0

**Comment by cap10morgan** [comment]
Great, thanks!
